version: "3.9"
volumes:
  bundle_cache:
    driver: local
  node_modules:
    driver: local
networks:
  main:
    name: main
    external: true
services:
  mailcatcher:
    working_dir: /
    image: mailcatcher
    build:
      context: .
      args:
        - ENVIRONMENT=development
    stdin_open: true
    tty: true
    ports:
      - "1080:1080" # API
      - "1025:1025" # SMTP
      - "3000:3000" # Web
    volumes:
      - ./server:/server:rw
      - ./webapp:/webapp:rw
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules:rw,delegated
    command: nf start
    env_file:
      - .env
    networks:
      - main