version: "3.9"
volumes:
  bundle_cache:
    driver: local
  node_modules:
    driver: local
networks:
  main:
    name: main
    external: true
services:
  server:
    extends:
      file: ./server/docker-compose.yml
      service: server
  webapp:
    extends:
      file: ./webapp/docker-compose.yml
      service: webapp

