name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Linting:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
      - name: Run Install
        run: |
          bundle install
      - name: Run Linter (rubocop)
        run: |
          bundle exec rubocop --parallel --fail-level warning --display-only-fail-level-offenses --format json -o report.json
      - name: Brakeman
        run: bundle exec brakeman --force
